import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
// import { PrismaClient } from "@prisma/client";

// const prisma = new PrismaClient();

export default function Home(props) {

    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');

    const save = async (e) => {
      e.preventDefault();

      const body = JSON.stringify({username, email});

      const res = await fetch('http://localhost:3000/api/user', {
        method: 'POST',
        mode: 'no-cors',
        body
      });

      const data = await res.json();
      console.log(data, 'data----');
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <div>
        {props.data.name}
       </div>

       <form>
          <input value={username} onChange={(e) => setUsername(e.target.value)}/>
          <input value={email} onChange={(e) => setEmail(e.target.value)} />
          <button onClick={save}>
            Save
          </button>
       </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getServerSideProps(context){
  const res = await fetch(`http://localhost:3000/api/hello`);
  const data = await res.json();

  return {
    props: {data}
  }
}
